Fix user CRUD and organized folders
ErickClinton/corporate-social-media-backend pull request #4
Opened 2024-02-13 21:21 UTC by JoaoVellenich

2024-02-13 22:12 UTC, ErickClinton requested changes

2024-02-13 22:12 UTC, ErickClinton commented on src/main/java/com/exampled/corporatesocialmedia/user/controllers/UserController.java
> +    @PostMapping("/register")
aqui pode pular linha
@Autowired
private DeleteUserUseCase deleteUserUseCase;

@PostMapping("/register")

2024-02-13 22:12 UTC, ErickClinton commented on src/main/java/com/exampled/corporatesocialmedia/user/useCase/CreateUserUseCase.java
> +    public void execute(CreateUserDTO dto) throws Exception {
acredito que seja melhor mudar o nome de dto para user.
Pois fica mais claro que e o dto do user

2024-02-13 22:12 UTC, ErickClinton commented on src/main/java/com/exampled/corporatesocialmedia/user/useCase/CreateUserUseCase.java
> +        return;
ja que é um void, pode tirar esse return

2024-02-13 22:12 UTC, ErickClinton commented on src/main/java/com/exampled/corporatesocialmedia/user/useCase/DeleteUserUseCase.java
> +
tirar o espaço entre os imports

2024-02-13 22:12 UTC, ErickClinton commented on src/main/java/com/exampled/corporatesocialmedia/user/useCase/ListAllUsersUseCase.java
> +
tirar um espaço aqui

2024-02-13 22:12 UTC, ErickClinton commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5434/corporate_social_media
tirar essas variaveis de ambiente aqui pra nao subir pro git

2024-02-14 13:43 UTC, JoaoVellenich commented on src/main/java/com/exampled/corporatesocialmedia/user/controllers/UserController.java
> +    @PostMapping("/register")
Isso você mesmo corrigiu

2024-02-14 17:17 UTC, ErickClinton approved these changes

2024-02-14 17:17 UTC, merged